requires:
  - type: git
    url: https://github.com/moremoban/pypi-mobans
    submodule: true
configuration:
  template_dir:
  - "pypi-mobans:templates"
  - ".moban.d"
  configuration: lml.yml
targets:
  - README.rst: CUSTOM_README.rst.jj2
  - setup.py: custom_setup.py.jj2
  - requirements.txt: requirements.txt.jj2
  - "docs/source/conf.py": "docs/source/custom_conf.py.jj2"
  - "docs/source/index.rst": "docs/source/custom_index.rst.jj2"
  - test.sh: test.sh.jj2
  - "lml/_version.py": _version.py.jj2
  - output: CHANGELOG.rst
    configuration: changelog.yml
    template: CHANGELOG.rst.jj2
