sudo: false
language: python
notifications:
  email: false
python:
  - 3.9-dev
  - 3.8
  - 3.7
  - 3.6
before_install:
  - pip install -r tests/requirements.txt
script:
  - make test
  - make -C examples/robotchef_allinone
  - make -C examples
  - make -C examples/v2
  - make -C examples/robotchef_allinone_lml
after_success:
  codecov
